version: '3'
services:
  nats:
    image: 'nats:linux'
    container_name: nats.local
    expose:
      - "4222"
    ports:
      - "4222:4222"
    networks:
     - net1
  # consul:
    # image: 'consul:latest'
    # ports:
      # - "8500:8500"
      # - "8600:8600"
    # environment:
      # CONSUL_BIND_INTERFACE: eth0
    # networks:
      # - net1
  staxx:
    image: makerdao/staxx:dev
    container_name: staxx.local
    depends_on:
      - nats
    expose:
      - "9100-9100"
    ports:
      # - "4369:4369"
      # - "9100:9100"
      - "4000:4000"
    environment:
      NATS_URL: nats.local
      DOCKER_DEV_MODE_ALLOWED: "true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "/tmp/chains:/opt/chains"
      - "/tmp/snapshots:/opt/snapshots"
      - "/tmp/stacks:/opt/stacks"
    networks:
     - net1
  ex_testchain:
    image: makerdao/ex_testchain:dev
    container_name: ex-testchain.local
    expose:
      - "8500-8600"
      - "9100-9100"
    ports:
      - "8500-8600:8500-8600"
      # - "9100-9105:9100-9105"
    # environment:
    #   FRONT_URL: localhost
    volumes:
      - "/tmp/chains:/opt/chains"
      - "/tmp/snapshots:/opt/snapshots"
    networks:
     - net1
  testchain-deployment:
    image: makerdao/testchain-deployment:dev
    container_name: testchain-deployment.local
    ports:
      - "5001:5001"
    environment:
      TCD_GATEWAY: host=staxx.local
      GITHUB_DEFAULT_CHECKOUT_TARGET: master
    volumes:
      - nix-db:/nix
    tmpfs:
      - /tmp
    depends_on:
      - nats
    networks:
     - net1
  testchain-dashboard:
    image: makerdao/testchain-dashboard
    container_name: testchain-dashboard.local
    expose:
      - "3000"
    ports:
      - "4001:3000"
    depends_on:
      - staxx
    environment:
      TESTCHAIN_SERVICE_URL: http://localhost
      TESTCHAIN_SERVICE_PORT: 4000
      TESTCHAIN_SERVICE_WS_URL: ws://localhost:4000/socket
    networks:
     - net1
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
        - ./metrics_config/prometheus.yml:/etc/prometheus/prometheus.yml
    # command:
        # - '-config.file=/etc/prometheus/prometheus.yml'
    ports:
        - '9090:9090'
    networks:
      - net1
  grafana:
    image: grafana/grafana
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - "3001:3000"
    volumes:
      # - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./metrics_config/grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
    networks:
      - net1

# We're using custom network setup, as it ships with a DNS
# system which allows containers to communicate by hostnames.
networks:
  net1:
    driver: bridge

volumes:
  nix-db:
